update to actions

diff --git a/.github/workflows/coverage.yml b/.github/workflows/coverage.yml
--- a/.github/workflows/coverage.yml
+++ b/.github/workflows/coverage.yml
@@ -1,30 +1,29 @@
-# This is a basic workflow to help you get started with Actions
-
 name: coverage
 
-# Controls when the workflow will run
 on:
-  # Triggers the workflow on push or pull request events but only for the development branch
+  # Trigger the workflow on push or pull request for development branch
   push:
     branches: [ development ]
+    paths-ignore:  # ignore paths that don't contain application code
+      - "tests/**"
+      - ".github/**"
   pull_request:
     branches: [ development ]
+    paths-ignore:  # ignore paths that don't contain application code
+      - "tests/**"
+      - ".github/**"
 
-  # Allows you to run this workflow manually from the Actions tab
+  # Allow manual job start
   workflow_dispatch:
 
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  # This workflow contains a single job called "build"
-  build:
-    # The type of runner that the job will run on
+  coverage:
     runs-on: ubuntu-latest
 
     env:
       COVERAGE_SINGLE: 60
       COVERAGE_TOTAL: 60
 
-    # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
       - name: Checkout repo
         uses: actions/checkout@v2
@@ -47,13 +46,7 @@ jobs:
           # fail if the total coverage is less than threshold
           cov-threshold-total: ${{ env.COVERAGE_TOTAL }}
 
-      - name: Single file coverage failure - exit
-        if: ${{ steps.pytester-cov.outputs.cov-threshold-single-fail == 'true' }}
-        run: |
-          echo "single file coverage failure"
-          exit 1
-
-      - name: Coverage single file failure - new issue
+      - name: Single file coverage failure - new issue
         if: ${{ steps.pytester-cov.outputs.cov-threshold-single-fail == 'true' }}
         uses: nashmaniac/create-issue-action@v1.1
         with:
@@ -62,6 +55,12 @@ jobs:
           assignees: ${{github.actor}}
           labels: workflow-failed
           body: ${{ steps.pytester-cov.outputs.output-table }}
+
+      - name: Single file coverage failure - exit
+        if: ${{ steps.pytester-cov.outputs.cov-threshold-single-fail == 'true' }}
+        run: |
+          echo "single file coverage failure"
+          exit 1
 
       - name: Total coverage failure - new issue
         if: ${{ steps.pytester-cov.outputs.cov-threshold-total-fail == 'true' }}
